fix/parsec: ensure benchmarks reach same consensus as .dot file
The series of benchmark with different section size aims to provide
scalability information. This only work if they reach the same
consensus.

Consensus can be reached before the create_sync_event occurs.
In this case, the dot file replay needs to create a new request so all
the gossip event that were processed to reach the consensus are given.

This request could be considered as spam as it will send events from
multiple nodes that do not have a common parent.

cargo test
cargo bench --test (no pannic)

When there is a problem, the benchmark fails with:
"
thread 'main' panicked at 'assertion failed: `(left == right)`
left: `(9, [a9d4c41b69.., e2eabbc898.., d08b8bc951.., 2de98dadad..,
8df8111faf.., c93ff2cda7.., 536064db2b.., 9daa8f8e91..])`,
 right: `(1, [a9d4c41b69..])`', benches/bench.rs:141:17
"